// ==============================================
// Copyright 2004 by CodeLifter.com
// Free for all; but please leave in this header.
// ==============================================

var Quotation=new Array() // do not change

Quotation[1] = "@jpfit_4life You can stop sinus congestion in its tracks.   Here is a recipe for a smoothie that can help you do just that:  - 2 carrots - 2 oranges - 1 green apple - 1 small piece of ginger  Mix it all,  And you have one great antidote to your sinus problems.   #jpfit4life #healthandwellnesshttps://twitter.com/jpfit_4life/status/1444438751342731266 ";
Quotation[2] = "@mindsetsasha Perfectionism kills you twice.  1. When you're procrastinating and stressing out. 2. When you're left with no progress due to #1.  Understand this and JUST. GET. STARTED.  70% is good enough.https://twitter.com/mindsetsasha/status/1444678834939441152 ";
Quotation[3] = "@bandz654 I dont have time¦ Has got to be the most widely used excuse out there. People need to give that excuse up. Anyone can find the time. Its just not a priority to you. You arent fooling anyone with the I dont have time excuse part.https://twitter.com/bandz654/status/1444700745383743492 ";
Quotation[4] = "@joe_lampton My reply to a young guy that asked for advice. https://t.co/jN87ExAoRWhttps://twitter.com/joe_lampton/status/1444725756177883144 ";
Quotation[5] = "@bandz654 If you know you should be further in life, but you keep letting you slide. Hold you accountable and dont let you off the hook. If for 5 yrs you didnt avoid doing what you knew you needed to do, what would you be like?https://twitter.com/bandz654/status/1444781609564114948 ";
Quotation[6] = "@markallanbovair My life started to improve dramatically when I quit zoning out in front of the TV for 3 hours every night. I always thought it was normal because thats what everyone does. I still watch an hour each night, but I got 2 hours a night or 60 hours a month back.https://twitter.com/markallanbovair/status/1444806539416641536 ";
Quotation[7] = "@jpfit_4life Do throw away your orange peel quite yet.   After you eat an orange,  Rub the peel on your teeth to clean your tooth enamel.   It whitens teeth, fights bacteria, and tackles stains.   This happens because of vitamin C, pectin, limonene, gluconate, and soluble fiber.  #jpfit4lifehttps://twitter.com/jpfit_4life/status/1444831513456136192 ";
Quotation[8] = "@THEROSSHARKNESS My weeks got a whole lot more productive once I started planning them out  My days got a whole lot more productive once I started planning them out  My goals started getting smashed once I started planning them out   Basically, plan more, achieve more.https://twitter.com/THEROSSHARKNESS/status/1444829885004976129 ";
Quotation[9] = "@Moneybaglives A Rule For Life:  Don't go to sleep with work overdue.  Go to sleep when It's done.https://twitter.com/Moneybaglives/status/1444111916914327557 ";
Quotation[10] = "@deprocrastinate Procrastination researcher Tim Pychil in the Procrastinators Digest suggests adopting this rule for yourself:  IF I say to myself things like, Ill feel more like doing this later or I dont feel like doing this now, THEN I will just get started on some aspect of the task.https://twitter.com/deprocrastinate/status/1445422607260700673 ";
Quotation[11] = "@finance_hipster My main retirement holdings are in two funds:  $VTI (Total US stock, 70%) $VXUS (International, 30%)  It makes it super easy to allocate money to them ” especially built together in one account.  Its the account I feel most comfortable in long term.https://twitter.com/finance_hipster/status/1445382590655963137 ";
Quotation[12] = "@numerology07 10x your Magic results:  Aries: Use Candle Taurus: Magic ritual in Gaden Gemini: Writing down intentions Cancer: Use Water Leo: Use Mantras  Virgo: clean surroundings Libra: Use Vision board Sco:maintain secrecy Cap: Ceremonial Magic Aqu: Group magic Pisces: Magic before sleephttps://twitter.com/numerology07/status/1445722507944759300 ";
Quotation[13] = "@LoftedLearning Make $1000s selling landing pages online:   practice making landing pages on Carrd for a month (one page a week)  find a product on Gumroad and make a landing page for it (framework below)  reach out to the creator and offer to give them access to the page  1/6https://twitter.com/LoftedLearning/status/1445728808179404818 ";
Quotation[14] = "@camduncannnn How I structure my landing pages when working with service businesses.  Feel free to save these images for your next project.  ðŸ‘‡ðŸ‘‡ https://t.co/iLe4Vz329Ohttps://twitter.com/camduncannnn/status/1446079980165869577 ";
Quotation[15] = "@jpfit_4life If you want more energy,   Wear the color orange.   It could be a shirt, shorts, socks, or any other piece of clothing.   It is scientifically proven to give you more energy in your day than any other color.https://twitter.com/jpfit_4life/status/1446148712099635205 ";
Quotation[16] = "@deprocrastinate 3 tips visualized:  1. Procrastination = symptom  You procrastinate for a reason. You might be overwhelmed. Or easily distracted. Or afraid of failure.  If you can pinpoint the deeper cause, you can address it better.  Don't judge yourself, ask: why am I putting this off? https://t.co/wfVlJBypkXhttps://twitter.com/deprocrastinate/status/1446144552188841988 ";
Quotation[17] = "@L0m3z For a deeper discussion of the matter https://t.co/tabHieBN9Shttps://twitter.com/L0m3z/status/1445892166232915973 ";
Quotation[18] = "@PhDGreg @kobegatsby You IT guys just sit around all day  okay, you do it  Ah idk what the hell Im doing with computers!https://twitter.com/PhDGreg/status/1446330784344907778 ";
Quotation[19] = "@joe_lampton Girls usually break up with guys   Then have them beg through the phone   Then they mentally torture them by going to parties &amp posting from other men's cars  If you simply ignore her &amp fuck better bitches  YOU WIN. SHE'LL START THINKING OF YOU EVERY DAY.  She's not used to this.https://twitter.com/joe_lampton/status/1446477285238915076 ";
Quotation[20] = "@jpfit_4life AFFIRM:   I like to be productive.https://twitter.com/jpfit_4life/status/1446498394176901121 ";
Quotation[21] = "@numerology07 Zodiac Signs you can overpower:  Aries -Capricorn Taurus -Pisces Gemini- Virgo Cancer- Taurus Leo- Aries Libra- Pisces Sco-Capricorn Sag-Cancer Cap-Taurus Aqu-Taurus Pis-Cancer  #AdvancedAstrology #SiderealZodiachttps://twitter.com/numerology07/status/1446524546186502148 ";
Quotation[22] = "@DMRHerbs Would it help the jabbed (vaxxed) to burn (in a diffuser) essential oil of Star Anise, Fennel (Sweet Fennel) and Pine Needle? Heck yeah! Its aromatherapy, the first healing modality used by man.https://twitter.com/DMRHerbs/status/1446548215369650177 ";
Quotation[23] = "@AJA_Cortes DEADLIFTING TIP:  Use a double overhand grip. A mixed grip might be stronger, but it always has an inherent risk of a bicep tear  If double overhand is difficult, use straps, &amp get your grip stronger  Unless you plan on competing in powerlifting, No one cares that you use strapshttps://twitter.com/AJA_Cortes/status/1446575991887958016 ";
Quotation[24] = "@joe_lampton Burpees in the mountains   One or the best workout routines ( although I hate it cause its hard)   Also   Training outdoor, barefoot, in the sun - increases your testosterone levels  Try it out. https://t.co/u4bwNCyIx1https://twitter.com/joe_lampton/status/1446584933758144514 ";
Quotation[25] = "@joe_lampton Winning and comfort aren't best friends   Train even if you feel like skipping the workout  Eat that 5th meal, although you're not hungry  Wake up early even though you want to postpone it  Do what has to be done.   Your future self will thank you for this.https://twitter.com/joe_lampton/status/1446626268406030342 ";
Quotation[26] = "@Moneybaglives Lifehack:  Get all your work done before checking Social Media  You'll be:   More Productive   More Present  More efficient  Try it for a weekhttps://twitter.com/Moneybaglives/status/1446627270987329538 ";
Quotation[27] = "@DMRHerbs The Universe responds to our dominant vibration on every subject. Strengthen your vibration for what you want and lessen your vibration towards what you do not want.https://twitter.com/DMRHerbs/status/1446632287555121154 ";
Quotation[28] = "@camduncannnn Why we make landing pages for e-commerce products rather than sending them directly to a store or collection page  ðŸ‘‡ðŸ‘‡ https://t.co/MBPLRk5JKMhttps://twitter.com/camduncannnn/status/1446831273750630410 ";
Quotation[29] = "@omnivoyance The more I learn about the digestive system the more I realize most bad eating habits stem from not properly chewing your foodhttps://twitter.com/omnivoyance/status/1446859484505202690 ";
Quotation[30] = "@SolBrah if you are feeling low energy literally just start jumping up and down and try and get as high as you can  do that for a few minutes  better than a coffeehttps://twitter.com/SolBrah/status/1446996915954978820 ";
Quotation[31] = "@DMRHerbs When youve developed yourself as a person/human being and you go out in the public amongst others human beings who are obviously underdeveloped (as they wasted and waste their time on liability activity/pursuits) its straight torture.https://twitter.com/DMRHerbs/status/1447079131334598658 ";
Quotation[32] = "@findgg33 Basic Numerology  1 = I argue 2 = I compromise 3 = I am funny 4 = I am the Law 5 = I am a Sexual 6 = I am Family 7 = I am a loner 8 = I been Poor and Rich 9 = I adapt  11 = I have charisma 22 = I build up others 33 = I influencehttps://twitter.com/findgg33/status/1447187414632521728 ";
Quotation[33] = "@3Ngx28 BE A DOER  … The SINGLE BIGGEST THING that differentiates the successful from unsuccessful is THEY ARE DOERS  … VERY FEW PEOPLE ARE  … Everything else - work ethic, brains, consistency - is a second derivative  … DOERS HAVE A TICKET FOR THE LOTTERYhttps://twitter.com/3Ngx28/status/1447484524447862786 ";
Quotation[34] = "@javyandrade October 22 is around the corner and happy to report that this experiment worked out.  Used my crypto as collateral and borrowed $500 at 1%.  Bought more #BTC at $12,887.34  After 1 year the $500 became $2100   Got 2 other loans maturing next year. https://t.co/9nmloo0nWThttps://twitter.com/javyandrade/status/1447621770480128005 ";
Quotation[35] = "@luisthewiz Don't sell web design services.  Sell conversion centered sales pages for infoproducts.  Sell lead-generating websites for accountants.  Sell appointment-generating landing pages for marketing agencies.  Smaller niche = More $$$.https://twitter.com/luisthewiz/status/1447624295966986246 ";
Quotation[36] = "@jpfit_4life Happy Motivational Monday!   I know it can be tough to wake up before 5 am.   I know it can be easier just to hit that snooze button and say that tomorrow will be the day I will start waking up early.   You tell yourself day after day,  And it just never happens. https://t.co/YXD1XiwPIfhttps://twitter.com/jpfit_4life/status/1447701287605309445 ";

// ======================================
// Do not change anything below this line
// ======================================
var Q = Quotation.length;
var whichQuotation=Math.round(Math.random()*(Q-1));
function showQuotation(){document.write(Quotation[whichQuotation]);}
showQuotation();
